/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatsRouteImport } from './routes/_chats'
import { Route as ChatsIndexRouteImport } from './routes/_chats/index'
import { Route as ChatsChatChatIdRouteImport } from './routes/_chats/chat/$chatId'

const ChatsRoute = ChatsRouteImport.update({
  id: '/_chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRoute,
} as any)
const ChatsChatChatIdRoute = ChatsChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => ChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatsIndexRoute
  '/chat/$chatId': typeof ChatsChatChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ChatsIndexRoute
  '/chat/$chatId': typeof ChatsChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chats': typeof ChatsRouteWithChildren
  '/_chats/': typeof ChatsIndexRoute
  '/_chats/chat/$chatId': typeof ChatsChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$chatId'
  id: '__root__' | '/_chats' | '/_chats/' | '/_chats/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatsRoute: typeof ChatsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chats': {
      id: '/_chats'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chats/': {
      id: '/_chats/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/_chats/chat/$chatId': {
      id: '/_chats/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatsChatChatIdRouteImport
      parentRoute: typeof ChatsRoute
    }
  }
}

interface ChatsRouteChildren {
  ChatsIndexRoute: typeof ChatsIndexRoute
  ChatsChatChatIdRoute: typeof ChatsChatChatIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsIndexRoute: ChatsIndexRoute,
  ChatsChatChatIdRoute: ChatsChatChatIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatsRoute: ChatsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
